version: 2.1

orbs:
  node: circleci/node@4.1
  blackduck: signavio/blackduck@1.3.0

references:
  workspace_root: &workspace_root ~/repo

jobs:
  build-and-black-duck-scan:
    working_directory: *workspace_root
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run build
          command: yarn build
      - blackduck/blackduck-detect:
          blackduck-project-group: SAP_PROCESS_MANAGER_OD_2.0
          blackduck-project-name: binge
          blackduck-project-path: *workspace_root

workflows:
  black-duck-scan:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build-and-black-duck-scan:
          context: BlackDuck
